### PR TITLE
Fix error propagation

### PR DESCRIPTION
**Pull request by binarin**
Errors from Text::CSV_XS were silently treated as an implicit
end-of-file and completely ignored, making it impossible to detect
that a whole file wasn't read.

This commit fixes it, making the following code piece from
documentation work as intended:

```perl
    while ( my $value = $parser->fetch ) { #...
    }
    if ( $parser->errstr ) { # Handle errors...
    }
```

### CODE REVIEW

**Comment by kenahoo** [comment]
Looks great, thanks.

**Comment by binarin** [comment]
@kenahoo if it's not too much hassle, can you please release a new version on CPAN?

**Comment by kenahoo** [comment]
I've been trying - it's been a while since I've released, and I ran into issues installing `Dist::Zilla`: https://rt.cpan.org/Ticket/Display.html?id=125678&results=ea3dfd373a3748986b02fbcb2dd39a9c

Will give it another shot.

**Comment by kenahoo** [comment]
Hi @binarin, the new version is released.

**Pull request merged**
